"""empty message

Revision ID: 226327a97cdb
Revises: 18bd21ccd491
Create Date: 2016-08-31 12:51:59.226607

"""

# revision identifiers, used by Alembic.
revision = '226327a97cdb'
down_revision = '18bd21ccd491'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registered_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registered_date', mysql.DATETIME(), nullable=False))
    ### end Alembic commands ###
