"""empty message

Revision ID: 679e6d016327
Revises: a5a1b4feba5f
Create Date: 2016-09-01 10:43:24.312251

"""

# revision identifiers, used by Alembic.
revision = '679e6d016327'
down_revision = 'a5a1b4feba5f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_unique_constraint(None, 'roles', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    ### end Alembic commands ###
