"""empty message

Revision ID: 8cb560abfb1a
Revises: 712d7a4344e7
Create Date: 2016-08-31 09:48:48.604759

"""

# revision identifiers, used by Alembic.
revision = '8cb560abfb1a'
down_revision = '712d7a4344e7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.TEXT(), nullable=False))
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
