"""empty message

Revision ID: a5a1b4feba5f
Revises: 226327a97cdb
Create Date: 2016-08-31 23:39:19.555442

"""

# revision identifiers, used by Alembic.
revision = 'a5a1b4feba5f'
down_revision = '226327a97cdb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
